# Generated by Django 5.1.2 on 2024-10-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0002_encuentrame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.IntegerField(choices=[('M', 'Masculino'), ('F', 'Femenino')])),
            ],
        ),
        migrations.DeleteModel(
            name='Encuentrame',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
