# Generated by Django 5.1.2 on 2024-10-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0003_personas_delete_encuentrame_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='genero',
            field=models.IntegerField(choices=[('M', 'Masculino'), ('F', 'Femenino')], verbose_name='Genero'),
        ),
    ]
