# Generated by Django 5.1.2 on 2024-10-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0004_alter_personas_email_alter_personas_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personas',
        ),
    ]
