# Generated by Django 5.1.2 on 2024-10-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0010_usuario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
