# Generated by Django 5.1.2 on 2024-10-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0011_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default=11, max_length=11, verbose_name='Cedula'),
            preserve_default=False,
        ),
    ]
