# Generated by Django 5.1.2 on 2024-10-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0012_usuario_cedula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Busqueda',
        ),
    ]
