# Generated by Django 5.1.2 on 2024-10-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0013_delete_busqueda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, verbose_name='Cedula'),
        ),
    ]
