# Generated by Django 5.1.2 on 2024-11-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0015_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivos/', verbose_name='Archivo'),
        ),
    ]
